// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogDocumentDataSlicesSlice = BlogSliceSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>; /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type ContentpageDocumentDataSlicesSlice = CreacionSliceSlice;

/**
 * Content for ContentPage documents
 */
interface ContentpageDocumentData {
  /**
   * Slice Zone field in *ContentPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contentpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContentpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *ContentPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contentpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ContentPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contentpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ContentPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contentpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ContentPage document from Prismic
 *
 * - **API ID**: `contentpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentpageDocumentData>,
    "contentpage",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = BlogContainerSlice | HeroSliceSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | ContentpageDocument
  | HomepageDocument;

/**
 * Default variation for AbaloriosSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AbaloriosSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *AbaloriosSlice*
 */
type AbaloriosSliceSliceVariation = AbaloriosSliceSliceDefault;

/**
 * AbaloriosSlice Shared Slice
 *
 * - **API ID**: `abalorios_slice`
 * - **Description**: AbaloriosSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AbaloriosSliceSlice = prismic.SharedSlice<
  "abalorios_slice",
  AbaloriosSliceSliceVariation
>;

/**
 * Item in *BlogContainer → Default → Primary → BlogPreview*
 */
export interface BlogContainerSliceDefaultPrimaryBlogpreviewItem {
  /**
   * Thumbnail field in *BlogContainer → Default → Primary → BlogPreview*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_container.default.primary.blogpreview[].thumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * BlogTitle field in *BlogContainer → Default → Primary → BlogPreview*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_container.default.primary.blogpreview[].blogtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blogtitle: prismic.KeyTextField;

  /**
   * BlogDescription field in *BlogContainer → Default → Primary → BlogPreview*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_container.default.primary.blogpreview[].blogdescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  blogdescription: prismic.RichTextField;
}

/**
 * Primary content in *BlogContainer → Default → Primary*
 */
export interface BlogContainerSliceDefaultPrimary {
  /**
   * title field in *BlogContainer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_container.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * BlogPreview field in *BlogContainer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_container.default.primary.blogpreview[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blogpreview: prismic.GroupField<
    Simplify<BlogContainerSliceDefaultPrimaryBlogpreviewItem>
  >;
}

/**
 * Default variation for BlogContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogContainerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogContainerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogContainer*
 */
type BlogContainerSliceVariation = BlogContainerSliceDefault;

/**
 * BlogContainer Shared Slice
 *
 * - **API ID**: `blog_container`
 * - **Description**: BlogContainer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogContainerSlice = prismic.SharedSlice<
  "blog_container",
  BlogContainerSliceVariation
>;

/**
 * Item in *BlogSlice → Default → Primary → Repeatablecontent*
 */
export interface BlogSliceSliceDefaultPrimaryRepeatablecontentItem {
  /**
   * RepeaterImg field in *BlogSlice → Default → Primary → Repeatablecontent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.repeatablecontent[].repeaterimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  repeaterimg: prismic.ImageField<never>;

  /**
   * RepeaterLegend field in *BlogSlice → Default → Primary → Repeatablecontent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.repeatablecontent[].repeaterlegend
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  repeaterlegend: prismic.RichTextField;

  /**
   * RepeaterText field in *BlogSlice → Default → Primary → Repeatablecontent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.repeatablecontent[].repeatertext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  repeatertext: prismic.RichTextField;
}

/**
 * Item in *BlogSlice → Default → Primary → LinksGroup*
 */
export interface BlogSliceSliceDefaultPrimaryLinksgroupItem {
  /**
   * LinkThumbnail field in *BlogSlice → Default → Primary → LinksGroup*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.linksgroup[].linkthumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  linkthumbnail: prismic.ImageField<never>;

  /**
   * LinkTitle field in *BlogSlice → Default → Primary → LinksGroup*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.linksgroup[].linktitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  linktitle: prismic.KeyTextField;

  /**
   * LinkDescription field in *BlogSlice → Default → Primary → LinksGroup*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.linksgroup[].linkdescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  linkdescription: prismic.RichTextField;

  /**
   * Link field in *BlogSlice → Default → Primary → LinksGroup*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.linksgroup[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *BlogSlice → Default → Primary*
 */
export interface BlogSliceSliceDefaultPrimary {
  /**
   * PreTitle field in *BlogSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.pretitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  pretitle: prismic.RichTextField;

  /**
   * title field in *BlogSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *BlogSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * BlogHero field in *BlogSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.bloghero
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bloghero: prismic.ImageField<never>;

  /**
   * legend field in *BlogSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.legend
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  legend: prismic.RichTextField;

  /**
   * MainContent field in *BlogSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.maincontent
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  maincontent: prismic.RichTextField;

  /**
   * Repeatablecontent field in *BlogSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.repeatablecontent[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repeatablecontent: prismic.GroupField<
    Simplify<BlogSliceSliceDefaultPrimaryRepeatablecontentItem>
  >;

  /**
   * YouTubeEmbed field in *BlogSlice → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.youtubeembed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  youtubeembed: prismic.EmbedField;

  /**
   * LinksGroup field in *BlogSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slice.default.primary.linksgroup[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  linksgroup: prismic.GroupField<
    Simplify<BlogSliceSliceDefaultPrimaryLinksgroupItem>
  >;
}

/**
 * Default variation for BlogSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogSlice*
 */
type BlogSliceSliceVariation = BlogSliceSliceDefault;

/**
 * BlogSlice Shared Slice
 *
 * - **API ID**: `blog_slice`
 * - **Description**: BlogSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSliceSlice = prismic.SharedSlice<
  "blog_slice",
  BlogSliceSliceVariation
>;

/**
 * Primary content in *ContentSlice → Default → Primary*
 */
export interface CreacionSliceSliceDefaultPrimary {
  /**
   * title field in *ContentSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creacion_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * HeroImg field in *ContentSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: creacion_slice.default.primary.heroimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  heroimg: prismic.ImageField<never>;

  /**
   * legend field in *ContentSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creacion_slice.default.primary.legend
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  legend: prismic.RichTextField;

  /**
   * Content field in *ContentSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creacion_slice.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for ContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CreacionSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CreacionSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentSlice*
 */
type CreacionSliceSliceVariation = CreacionSliceSliceDefault;

/**
 * ContentSlice Shared Slice
 *
 * - **API ID**: `creacion_slice`
 * - **Description**: CreacionSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CreacionSliceSlice = prismic.SharedSlice<
  "creacion_slice",
  CreacionSliceSliceVariation
>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * TopImage field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.topimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  topimage: prismic.ImageField<never>;

  /**
   * BackgroundImage field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.backgroundimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundimage: prismic.ImageField<never>;

  /**
   * title field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      ContentpageDocument,
      ContentpageDocumentData,
      ContentpageDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AbaloriosSliceSlice,
      AbaloriosSliceSliceVariation,
      AbaloriosSliceSliceDefault,
      BlogContainerSlice,
      BlogContainerSliceDefaultPrimaryBlogpreviewItem,
      BlogContainerSliceDefaultPrimary,
      BlogContainerSliceVariation,
      BlogContainerSliceDefault,
      BlogSliceSlice,
      BlogSliceSliceDefaultPrimaryRepeatablecontentItem,
      BlogSliceSliceDefaultPrimaryLinksgroupItem,
      BlogSliceSliceDefaultPrimary,
      BlogSliceSliceVariation,
      BlogSliceSliceDefault,
      CreacionSliceSlice,
      CreacionSliceSliceDefaultPrimary,
      CreacionSliceSliceVariation,
      CreacionSliceSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
    };
  }
}
