// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  abalorios_slice: dynamic(() => import("./AbaloriosSlice")),
  blog_container: dynamic(() => import("./BlogContainer")),
  blog_slice: dynamic(() => import("./BlogSlice")),
  creacion_slice: dynamic(() => import("./ContentSlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
};
